### ISSUE TITLE
Where're so many listeners being added for the same event?

### ISSUE THREAD

**Issue by ZhouHansen** [jimpick/dat-shopping-list#60]
https://github.com/jimpick/dat-shopping-list/blob/92b7678967b2c9bdc5341caa1f60d49cd1304106/server/index.js#L17

I just want to ask is this line of code necessary?

**Comment by jimpick** [comment]
It suppresses a warning. More than 10 listeners get added due to the peer-to-peer nature of the networking.

It would be better to use .setMaxListeners(0) on the specific event source that was causing the warnings.

https://nodejs.org/dist/latest-v10.x/docs/api/events.html#events_emitter_setmaxlisteners_n

**Comment by ZhouHansen** [comment]
the peer-to-peer nature of the networking. Thanks, I'll dive into it later.
